project:
  type: book
  output-dir: docs  # This tells Quarto to put the book output in the 'docs/' folder

book:
  title: "ABCD Codebook: R01MH134039"
  author: "Katherine Schaumberg"
  date: "2025"
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - 02-cohort-profile.qmd
    - 03-ed-data.qmd
    - 04-internalizing.qmd
    - 05-externalizing.qmd
    - 06-anthropometry.qmd
    - 07-physical-activity.qmd
    - 08-sociodemographics.qmd
    - 09-genomic_data.qmd
  repo-url: https://github.com/GENIE-Grant/ABCD_codebook
  repo-actions: [edit, issue]

format:
  html:
    theme: default
    toc: true
    number-sections: true
  pdf:
    documentclass: book
    number-sections: true

bibliography: ["ABCD.bib", "packages.bib"]
csl: academic-medicine.csl
link-citations: true
